unhelpful "no configuration has been provided" when no current-context is set
Sometimes, my ~/.kube/config doesn't have a current-context set. When I run
kubectl, I get an error message that helps me debug the problem:

  $ kubectl config view --minify --flatten
  error: current-context must exist in order to minify

On the other hand, kubectl-incluster is less helpful:

  $ kubectl-incluster
  error: loading: error loading kube config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

This patch makes kubectl-incluster print a more helpful error message when
no current-context is set.